Repository woowa-techcamp-2021/cashbook-11, pull requests merged in 2021-07, with the labels that each got.

#3 [#2] REAMDE 를 통한 PR 탬플릿 동작 테스트
  README.md
Labels: documentation

#23 [#4] 클라이언트 구조 잡기(페어)
  .gitignore
  client/.babelrc
  client/.eslintrc.json
  client/.prettierrc.json
  client/dist/index.html
  client/dist/main.js
  client/package.json
  client/src/components/README.md
  client/src/constants/README.md
  client/src/core/component.ts
  client/src/index.html
  client/src/index.scss
  client/src/main.ts
  client/src/models/README.md
  client/src/reset.scss
  client/src/router.ts
  client/src/tsconfig.json
  client/src/utils/api.ts
  client/src/views/README.md
  client/webpack.config.js
Labels: Pair Programming, enviroment

#25 [#5] 백엔드 프로젝트 구조 잡기 완료
  .gitignore
  server/package.json
  server/src/app.js
  server/src/config/config_sample.json
  server/src/constants/error.js
  server/src/constants/success.js
  server/src/errors/custom-error.js
  server/src/middlewares/decode-jwt.js
  server/src/middlewares/error-handler.js
  server/src/models/index.js
  server/src/models/user.js
  server/src/routes/index.js
  server/src/routes/user-router.js
  server/src/services/user-service.js
  server/src/utils/bcrypt.js
  server/src/utils/jwt.js
Labels: Pair Programming, enviroment

#26 [#4] 클라이언트 구조 잡기
  client/src/components/base/appbar/index.scss
  client/src/components/base/appbar/index.ts
  client/src/components/base/fab/index.scss
  client/src/components/base/fab/index.ts
  client/src/components/calandar/index.scss
  client/src/components/calandar/index.ts
  client/src/components/sample.ts
  client/src/core/component.ts
  client/src/core/router.ts
  client/src/index.html
  client/src/main.ts
  client/src/pages/calendar.ts
  client/src/pages/home.ts
  client/src/pages/statistics.ts
  client/webpack.config.js
Labels: Pair Programming, enviroment

#27 [#4, #6] 회원가입 구현 및 프론트엔드 구조 잡기
  client/src/components/base/fab/index.ts
  client/src/index.html
  client/src/main.ts
  client/src/utils/api.ts
  client/src/utils/select.ts
Labels: Pair Programming, enviroment, feature

#28 [#4] 프론트엔드 구조 잡기 완성~~ 이얏호
  client/src/components/base/appbar/index.ts
  client/src/components/sample.ts
  client/src/core/component.ts
  client/src/core/observable.ts
  client/src/main.ts
  client/src/models/date-store.ts
  client/src/models/index.ts
  client/src/pages/home.ts
Labels: Pair Programming, enviroment

#29 [#5] timezone 설정 완성~~
  server/src/constants/common.js
  server/src/models/category.js
  server/src/models/history.js
  server/src/models/index.js
  server/src/models/pay-type.js
  server/src/models/user-pay-trend.js
  server/src/models/user-pay-type.js
  server/src/routes/calendar-router.js
  server/src/routes/home-router.js
  server/src/routes/statistics-router.js
  server/src/services/category-service.js
  server/src/services/history-service.js
  server/src/services/pay-type-service.js
  server/src/services/user-pay-trend-service.js
  server/src/services/user-pay-type-service.js
Labels: Pair Programming, enviroment

#31 분업 전 공통으로 필요한 프론트엔드 작업
  client/src/assets/calendar.svg
  client/src/assets/chart.svg
  client/src/assets/check.svg
  client/src/assets/chevron-down.svg
  client/src/assets/chevron-left.svg
  client/src/assets/chevron-right.svg
  client/src/assets/close.svg
  client/src/assets/file-text.svg
  client/src/components/base/daily-history/history/index.scss
  client/src/components/base/daily-history/history/index.ts
  client/src/components/base/daily-history/index.scss
  client/src/components/base/daily-history/index.ts
  client/src/components/calandar/content/index.scss
  client/src/components/calandar/content/index.ts
  client/src/components/calandar/daybar/index.scss
  client/src/components/calandar/daybar/index.ts
  client/src/components/calandar/footer/index.scss
  client/src/components/calandar/footer/index.ts
  client/src/components/home/content/index.scss
  client/src/components/home/content/index.ts
  client/src/components/home/filter/index.scss
  client/src/components/home/filter/index.ts
  client/src/components/home/searchbar/index.scss
  client/src/components/home/searchbar/index.ts
  client/src/components/statistics/ratio-chart/index.scss
  client/src/components/statistics/ratio-chart/index.ts
  client/src/components/statistics/trend-chart/index.scss
  client/src/components/statistics/trend-chart/index.ts
  client/src/index.scss
  client/src/main.ts
  client/src/reset.scss
Labels: Pair Programming, enviroment

#33 I10 appbar 현재까지 작업한 내용
  client/src/components/base/appbar/index.scss
  client/src/components/base/appbar/index.ts
  client/src/core/observable.ts
  client/src/core/router.ts
  client/src/main.ts
  server/src/routes/home-router.js
  server/src/routes/index.js
  server/src/services/history-service.js
Labels: feature

#34 회원가입 기능 추가
  client/src/components/base/fab/index.scss
  client/src/components/base/fab/index.ts
  client/src/components/base/modal/index.scss
  client/src/components/base/modal/index.ts
  client/src/index.html
  client/src/main.ts
  client/src/utils/selectHandler.ts
Labels: feature

#35 [#6] 회원가입 기능 구현
  client/src/components/base/modal/index.ts
  client/src/components/base/user-modal/index.scss
  client/src/components/base/user-modal/index.ts
  client/src/components/base/user-modal/modal-content/index.scss
  client/src/components/base/user-modal/modal-content/index.ts
  client/src/main.ts
Labels: feature

#36 [#7] 로그인 수정
  client/src/components/base/user-modal/modal-content/index.ts
  client/src/utils/cookie.ts
  server/src/constants/error.js
  server/src/constants/success.js
  server/src/services/user-service.js
  server/src/utils/jwt.js
Labels: feature

#39 버그 픽스로 인한 병현님과의 머지
  client/src/components/home/content/index.ts
  client/src/components/home/searchbar/index.scss
  client/src/components/home/searchbar/index.ts
  client/src/pages/home.ts
  server/src/routes/home-router.js
  server/src/services/history-service.js
  server/src/services/user-service.js
  server/src/utils/jwt.js
Labels: bug, feature

#50 I7 signin
  client/src/components/base/fab/index.ts
  client/src/components/base/snackbar/index.scss
  client/src/components/base/snackbar/index.ts
  client/src/components/base/user-modal/index.ts
  client/src/components/base/user-modal/modal-content/index.scss
  client/src/components/base/user-modal/modal-content/index.ts
  client/src/index.html
  client/src/utils/modal.ts
Labels: feature

#49 [#48] DB 구조 수정
  client/webpack.config.js
  server/src/models/index.js
  server/src/models/pay-type.js
Labels: bug, enviroment
